#services:
#  db:
#    image: mysql:8.0
#    environment:
#      - MYSQL_DATABASE=main
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=password
#      - MYSQL_ROOT_PASSWORD=root_password
#    ports:
#      - "3305:3306"
#    volumes:
#      - ./resources/db-migrations:/docker-entrypoint-initdb.d/
#    command: --default-authentication-plugin=mysql_native_password
#
#  redis:
#    image: redis:7-alpine
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#
#  backend:
#      build: .
#      ports:
#          - "8000:8000"
#      depends_on:
#            - db
#            - redis
#      environment:
#            - MYSQL_HOST=db
#            - REDIS_HOST=redis
#      volumes:
#            - .:/app
#      command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
#
#volumes:
#  mysql_data:
#  redis_data:
#  mysql-data:

version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
    - MYSQL_DATABASE=main
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    volumes:
      - ./resources/db-migrations:/docker-entrypoint-initdb.d/
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: .
    ports:
      - "8000:8000"   # FastAPI
      - "8501:8501"   # Streamlit
    depends_on:
      - db
      - redis
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=main
      - REDIS_HOST=redis

    volumes:
      - .:/app

volumes:
  redis_data:
  mysql-data: